### ISSUE TITLE
Please add netstandard2.0 target to NuGet package

### ISSUE THREAD

**Issue by springy76** [SixLabors/Core#17]
Adding any netstandard1.x package to a project only using netstandard2.0 refs tends to introduce some weird NuGet relationship hell which may output a large amount of unnecessary warnings upstream to all referencing projects.

Please just add the additional netstandard2.0 target.
Or maybe you just should change netcoreapp2.0 to netstandard2.0? It's a library, not an app. Even 100% of the ASP.NET Core 2.1 libs just target netstandard2.0.

**Comment by iamcarbon** [comment]
Agreed that we should cross target netstandard2.0 to avoid pulling in all the netstandard1.x bloat. I've submitted a PR for this.

We need to keep netcoreapp2.0 target to support MathF.

**Comment by JimBobSquarePants** [comment]
Fixed with #18 Thanks @iamcarbon
