### ISSUE TITLE
Beta5 introduces error with System.Buffers

### ISSUE THREAD

**Issue by ericdunn** [SixLabors/Core#21]
Hello All, 

I'm currently building an application that's targeting a few different framework versions, including .net 4.5.2. (we're stuck with this for a little while on that project).

We are getting this odd build issue when targetting version beta0005 of SixLabors.ImageSharp, which references SicLabors.Core version beta0006.

The issue is that when running under .net 4.5.2 (this may happen elsewhere too), we get the following error: 
`
Exception has been thrown by the target of an invocation.
There was an error trying to auto-sign the label file.
The type initializer for 'SixLabors.ImageSharp.Configuration' threw an exception.
Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
`

The version being loaded of System.Buffers is **4.0.3.0** and not 4.0.2.0, which is why things fail. If we copy 4.0.2.0 back in, everything seems to work just fine again. 

I reverted back to beta4 (which uses beta5 of core), and things are working again, everything is pointing back to the right versions. 

Any idea why this is happening?

Thanks!

**Comment by JimBobSquarePants** [comment]
What format is your csproj? The old package.config format or the new SDK  style?

If it's the old style, I would recommend using the new style and adding the following lines to the project file.

``` xml
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
```

**Comment by iamcarbon** [comment]
We may want to downgrade to System.Buffers to v4.4.0 to reduce the need for binding redirects. The library ecosystem never adopted v4.5.0.

PR coming.

**Comment by ericdunn** [comment]
Sorry for the late reply, I'm using the new style csproj.

**Comment by iamcarbon** [comment]
@ericdunn Did we resolve the conflict in Beta6?

**Comment by ericdunn** [comment]
I'll have a look at this tomorrow and will let you know!

Thanks!
Eric.

**Comment by ericdunn** [comment]
The problem now is that because of 
https://github.com/SixLabors/Core/commit/7443aefea06e04a1d0a7bac10b5e6026adb16de4
upping the min version to netstandard1.3 (.net 4.5.2 would be netstandard1.2), I can't install the package :/

**Comment by JimBobSquarePants** [comment]
I'm afraid you'll just have to update. 1.3 is our minimum, it all gets too complicated to build otherwise.
