### ISSUE TITLE
Missing contribution guidelines

### ISSUE THREAD

**Issue by synercoder** [SixLabors/Core#27]
I just created a pull request, I hope I did it correctly, my PR was based on the PR template for ImageSharp. This because this repo does not contain a PR template or any other contribution guidelines. 

Mayhaps interesting to add guidelines (or copy from ImageSharp) to encourage other people to contribute.

**Comment by JimBobSquarePants** [comment]
Hi @synercoder 

Thanks yes, we definitely need to update all our repositories to match. However, I cannot see your PR?

**Comment by JimBobSquarePants** [comment]
Ah, sorry i misunderstood. I thought you were PRing to add the contribution guidelines! I'll review your PR asap. Thanks for helping out!

**Comment by synercoder** [comment]
@JimBobSquarePants and now I also created a PR for the contribution guidelines.

**Comment by JimBobSquarePants** [comment]
Ah wizard. Thanks! 👍

**Comment by JimBobSquarePants** [comment]
Fixed with #29
