### ISSUE TITLE
Rectangle.Contains does not include right and bottom edges

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/Core#3]
currently we have 
```public bool Contains(int x, int y) => this.X <= x && x < this.Right && this.Y <= y && y < this.Bottom;```

should read 
```public bool Contains(int x, int y) => this.X <= x && x <= this.Right && this.Y <= y && y <= this.Bottom;```

**Comment by tocsoft** [comment]
Actually I think the issue is that the Right  & Bottom values are off by one

At the moment if the you have Rect @ 0,0 10x10 the Bottom & right are currently 10 when infact they should be 9.

**Comment by KingKnecht** [comment]
Is that true? if I have 0,0 and 1x1 the bottom and right should be "0" ? I think "<=" is correct.

**Comment by tocsoft** [comment]
I think they are both wrong but the fact the bottom & right are off by one makes the contains return the correct value.

**Comment by JimBobSquarePants** [comment]
Look correct to me.

[We have](https://github.com/SixLabors/Core/blob/f68740f0ee869f799069df81482be9d423622862/src/SixLabors.Core/Primitives/Rectangle.cs#L391)
``` c#
public bool Contains(int x, int y) => this.X <= x && x < this.Right && this.Y <= y && y < this.Bottom;
```
[`System.Drawing.Primitives` has](https://github.com/dotnet/corefx/blob/03d705664c6c14b3ac3b1c73caae69e91542f530/src/System.Drawing.Primitives/src/System/Drawing/Rectangle.cs#L260)
``` c#
public bool Contains(int x, int y) => X <= x && x < X + Width && Y <= y && y < Y + Height;
```

Our `Right` and `Bottom` properties match

``` c#
        /// <summary>
        /// Gets the x-coordinate of the right edge of this <see cref="Rectangle"/>.
        /// </summary>
        public int Right
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                return unchecked(this.X + this.Width);
            }
        }

        /// <summary>
        /// Gets the y-coordinate of the bottom edge of this <see cref="Rectangle"/>.
        /// </summary>
        public int Bottom
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get
            {
                return unchecked(this.Y + this.Height);
            }
        }
```

**Comment by JimBobSquarePants** [comment]
I'm closing this. I've double checked it against the `Sytem.Drawing.Primitives.Rectangle` and we match
