### ISSUE TITLE
Couldn't find assembly.

### ISSUE THREAD

**Issue by TurboLOL** [SixLabors/Core#9]
Exception: Could not load file or assembly 'SixLabors.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
I don't know why it is saying that. 
I tried reinstalling the package, but that didn't help.

**Comment by tocsoft** [comment]
Please can you provide more details about how/why you are trying to load SixLabors.Core. 

From that error it looks simply like you don't have the correct version of the dll in your bin folders.

Make sure you don't have more than one project with differing dependency versions as that can cause issues. For one make sure your only using the beta1/2 of the SixLabros.* packages from nuget as they will be the most stable/compatible with each other.

**Comment by tocsoft** [comment]
you should now only be using SixLabors.ImageSharp any other packages that don't have the sixlabors prefix are eather outdated or unofficial.

**Comment by TurboLOL** [comment]
Oh ok, thanks!
